# KEGG Functional Pathway Annotation and Analysis

```{r}
#| echo: false
#| eval: true
#| label: setup

# This initial code block loads custom utility functions and environment variables
# These are stored in separate files to keep the main analysis clean and organized
suppressWarnings(suppressMessages({
  source(normalizePath("utils/r-utils.r"))
  source(normalizePath("_environment.required"))
  load(normalizePath("data/seqdata.RData"))

  metadata <- read_delim(normalizePath(METADATA))

  dir.create(
    file.path(RESULTS, "KEGG-functional-analysis"),
    showWarnings = FALSE,
    recursive = TRUE
  )
}))
```

## Data preparation

Preparation of data from Woltka output for use in R

### Import annotation files

```{r}
#| eval: true
#| label: kegg pathway annotation files
pathways <- read.delim(
  file.path(REF, "/WoL2-Woltka/function/kegg", "pathway_name.txt"),
  header = F,
  col.names = c("id", "name")
)

path_class <- read.delim(
  file.path(REF, "/WoL2-Woltka/function/kegg", "pathway-to-class.map"),
  header = F,
  col.names = c("id", "group", "class")
)

pathways <- left_join(pathways, path_class) %>%
  dplyr::select(id, group, class, name)

write.csv(
  pathways,
  file.path(REF, "/WoL2-Woltka/function/kegg", "pathways.csv"),
  row.names = F
)
```

### Import Woltka KEGG pathway results

```{r}
#| eval: false
path_cov <- read_delim(file.path(WOLTKA_OUT, "kegg/pathway_coverage.tsv")) %>%
  pivot_longer(cols = !`#FeatureID`)

names(path_cov) <- c("ko", "sample", "percent_cov")

path_cov$sample <- str_remove_all(path_cov$sample, "_filtered")

write.csv(
  path_cov,
  file.path(RESULTS, "KEGG-functional-analysis/kegg-pathway-coverage-long.csv"),
  row.names = F
)
```

```{r}
#| eval: false
#| label: import KO files
ko <- read_delim(file.path(WOLTKA_OUT, "kegg/pathway.tsv")) %>%
  pivot_longer(cols = !`#FeatureID`)

names(ko) <- c("ko", "sample", "count")
ko$sample <- str_remove_all(ko$sample, "_filtered")

write.csv(
  ko,
  file.path(
    RESULTS,
    "KEGG-functional-analysis/kegg-pathway-ko-counts-long.csv"
  ),
  row.names = F
)
```

### Data preparation

```{r}
#| eval: true
#| label: kegg

kegg <- left_join(path_cov, ko) %>%
  mutate(
    count = ifelse(is.na(count), 0, count),
    sample = str_replace(
      str_replace(str_remove(sample, "_G"), "_B_B", "_B"),
      "_B_E",
      "_E"
    )
  ) %>%
  mutate(
    timepoint = metadata$timepoint[match(.$sample, metadata$sample_names)],
    trt = metadata$trt[match(.$sample, metadata$sample_names)],
    pathway_group = pathways$group[match(.$ko, pathways$id)],
    pathway_class = pathways$class[match(.$ko, pathways$id)],
    pathway_name = pathways$name[match(.$ko, pathways$id)]
  ) %>%
  mutate(pathway_class = coalesce(pathway_class, pathway_name)) %>%
  mutate(
    pathway_group = coalesce(pathway_group, pathway_class),
    arm = case_when(trt == 0 ~ "CPM", trt == 1 ~ "FeZnPM")
  )

saveRDS(kegg, file.path(WOLTKA_OUT, "kegg/kegg.rds"))
write.csv(
  kegg,
  file.path(
    RESULTS,
    "KEGG-functional-analysis/kegg-pathway-cov-ko-annotated-long.csv"
  ),
  row.names = F
)
```

There are `r length(unique(path_cov$sample))` samples in the dataset.