# Gene Ontology Enrichment

```{r}
#| echo: false
#| eval: true
#| label: setup
#| cache: false

# This initial code block loads custom utility functions and environment variables
# These are stored in separate files to keep the main analysis clean and organized
suppressWarnings(suppressMessages({
  source(normalizePath("utils/r-utils.r"))
  source(normalizePath("_environment.required"))
  load(normalizePath("data/seqdata.RData"))

  metadata <- read_delim(normalizePath(METADATA))

  go2kegg <- read.delim(
    file.path(REF, "WoL2-Woltka/function/go/idmaps/kegg.map"),
    header = T
  )

  library(promicrobialTools)
  prefix <- "GO-"

  filepath <- get_results_dir(directory_naming = "parent")
}))
```

Results will be saved to ``r filepath``.

## Data preparation

Preparation of data from Woltka output for use in R

### Load data

```{r}
#| eval: true
#| label: load data
go <- read.delim(file.path(WOLTKA_OUT, "go/all.generic.tsv"), header = T) %>%
  mutate_at(vars(everything()), str_trim, side = "both") %>%
  pivot_longer(
    cols = !c(Name, X.FeatureID),
    names_to = "sample",
    values_to = "count"
  ) %>%
  rename(Terms = Name, go_id = X.FeatureID) %>%
  mutate(sample = str_remove(sample, "_filtered")) %>%
  mutate(
    sample = str_replace(
      str_replace(str_remove(sample, "_G"), "_B_B", "_B"),
      "_B_E",
      "_E"
    )
  ) %>%
  mutate_at(vars(everything()), type.convert, as.is = TRUE)
```

### Add additional metadata to data

```{r}
#| eval: true
#| label: assign ontology to GO IDs
go_onto <- clusterProfiler::go2ont(go$go_id)

go <- go %>%
  mutate(
    timepoint = metadata$timepoint[match(.$sample, metadata$sample_names)],
    trt = metadata$trt[match(.$sample, metadata$sample_names)],
    kegg_rxn_id = go2kegg$kegg_rxn_id[match(.$go_id, go2kegg$go_id)],
    arm = case_when(trt == 0 ~ "CPM", trt == 1 ~ "FeZnPM"),
    ontology = go_onto$Ontology[match(go_id, go_onto$go_id)]
  ) %>%
  mutate(
    ontology = case_when(
      ontology == "MF" ~ "Molecular function",
      ontology == "BP" ~ "Biological process",
      ontology == "CC" ~ "Cellular component"
    )
  )
```

```{r}
#| eval: true
#| label: save
#| results: asis

save_and_link(
  data = go,
  filename = paste0(prefix, "processed-all.generic.csv"),
  description = "Processed GO terms (MF, BP, CC)",
  directory_naming = "both"
)
```

#### GO subsets

```{r}
#| eval: true
#| label: baseline-go

go_base <- go %>%
  dplyr::filter(timepoint == "Baseline")
```

```{r}
#| eval: true
#| label: save-base-go
#| results: asis

save_and_link(
  data = go_base,
  filename = paste0(prefix, "Baseline-annotated-go-terms.csv"),
  description = "Baseline GO Annotations",
  directory_naming = "both"
)
```

```{r}
#| eval: true
#| label: baseline-endpoint-go

go_be <- subset(
  subset(go, sample %in% base_end_paired_samples$sample),
  timepoint %in% c("Baseline", "Endpoint")
)
```

```{r}
#| eval: true
#| label: save-base-go
#| results: asis

save_and_link(
  data = go_be,
  filename = paste0(prefix, "EvsB-annotated-go-terms.csv"),
  description = "Paired Baseline and Endpoint GO Annotations",
  directory_naming = "both"
)
```

### Dataset filter

Filtering GO database to contain only bacterial GO terms using [GO slim prokaryote](https://geneontology.org/docs/download-ontology/). *downloaded 08-Oct-24*

```{bash}
#| eval: false
#| label: download GO slim

wget -P ref/ https://current.geneontology.org/ontology/subsets/goslim_prokaryote.tsv
```

```{r}
#| eval: true
#| label: annotation with only bacterial GO terms

annoBac <- read.delim(
  file.path(REF, "gene-ontology", "goslim_prokaryote.tsv"),
  col.names = c("go_id", "terms")
) %>%
  mutate(go_id = str_replace(str_extract(go_id, "GO_\\d*"), "_", ":"))
```

```{r}
#| eval: true
#| label: save
#| results: asis

save_and_link(
  data = annoBac,
  filename = paste0(prefix, "goslim_prokaryote-formatted.csv"),
  description = "",
  directory_naming = "both"
)
```