# Introduction

Previous iron supplemention studies in children have suggested adverse gut microbiota shifts (increased pathogens). Given iron’s importance in early childhood, particularly where iron deficiency and anemia are high, it is essential to test food-based approaches for similar impacts. Here, we report gut microbiome effects of 9 months’ daily consumption of iron/zinc-biofortified pearl millet (FeZnPM), compared to control pearl millet (CPM) in children living in urban slums of Mumbai, India as part of a randomized controlled feeding trial (NCT02233764).

Children (12–18 months, N=223, hemoglobin >9 g/dL) were randomized to receive FeZnPM or CPM-based foods (8.70 vs 3 mg Fe/100 g). Rectal swabs collected across follow-up underwent shotgun metagenomic sequencing, and assigned to operational genomic units (OGUs). Arm differences were examined using diversity indices, functional pathway and differential abundance analyses at and between baseline and endpoint. OGU and diversity differences were examined using mixed models, and endpoint KEGG pathways using co-occurrence networks. 

Children receiving FeZnPM showed distinct metabolic adaptations at study endpoint compared to CPM. The intervention group exhibited increased pathways for antibiotic biosynthesis (phenazine, monobactam) and antioxidant metabolism (glutathione, lipoic acid), indicating enhanced resistance to pathogens and an improved gut environment. Conversely, FeZnPM consumption was associated with decreased pathways for pollutant degradation (xylene, aminobenzoate) and reduced prodigiosin biosynthesis, consistent with reduced abundance of pathogenic bacteria. Independent of arm, the maturing microbiome showed increased diversity and enhanced metabolic capacity for processing diverse substrates and reduced reliance on host-derived substrates. 

This is one of the first studies known to us that examines the effect of  biofortified crops on the human gut microbiome. FeZnPM did not adversely affect the developing microbiota and may support beneficial metabolic adaptations. Thus, biofortified crops could be a sustainable approach to addressing iron deficiency while supporting microbiome development in early life.

::: {.callout-warning}
Samples from participant SO_8465_7114 (n=3) have been removed from the analysis due to issues with the sequence file in fact being a *de novo* assembly of MAGs, rather than raw sample reads. This was discovered during the course of the analysis, and is not reflected in the original metadata file. The sample was removed from all analyses and figures in this report.
:::