## Endpoint Bacterial Analysis

```{r}
#| echo: false
#| eval: true
#| label: setup
source("utils/r-utils.r")
source("_environment.required")
```

So that it can be directly compared to the endpoint sample in Base-End analysis only the samples that have a matching baseline sample will be included. Note that 27 individuals do not have baseline samples.

```{r eval = FALSE, label = "view baseline-endpoint pairs"}
tmp <- metadata %>% 
        select(sample_names, any_other_relevant_information) %>% 
        mutate(sample_names =str_remove_all(sample_names, "_wol_alignment|_M|_B|_E|_G")) %>% 
        filter(str_detect(any_other_relevant_information, "1Baseline|3Endpoint")) %>% 
        group_by(sample_names) %>% 
        mutate(value = case_when(any_other_relevant_information == "1Baseline" ~ 1, any_other_relevant_information == "3Endpoint" ~ 3)) %>% 
        pivot_wider(id_cols = sample_names, names_from=any_other_relevant_information)

sapply(tmp, function(x) sum(is.na(x)))
```

```{r eval=TRUE, label = "Endpoint Bacteria: subset data"}
#subset for individuals with a baseline and matvhing end point
#only 82 sample have matching baseline and endpoint samples
base_end_paired_samples <- 
  metadata %>% #whole dataset metadata file
  rownames_to_column() %>%
  dplyr::select(sample =rowname, timepoint = any_other_relevant_information) %>%
  mutate(sample = str_remove_all(sample, "_wol_alignment|_M|_B|_E|_G")) %>%
  mutate(sample = str_trim(sample, side = "both")) %>% 
  group_by(sample) %>%
  dplyr::filter(all(c("1Baseline", "3Endpoint") %in% timepoint)) %>%
  ungroup() #base-mid-end sample 

#dim(base_end_paired_samples)

end <- seqdata_bac
sample_data(end) <- cbind(sample_names = rownames(sample_data(end)), sample_data(end))
sample_data(end) <- as.data.frame(as.matrix(sample_data(end))) %>% 
  mutate(sample_names = str_remove_all(sample_names, "_wol_alignment|_M|_B|_E|_G")) %>%
  mutate(sample_names = str_trim(sample_names))

end <- phyloseq::subset_samples(end, sample_names %in% base_end_paired_samples$sample)#Base-Mid-End samples
end <- phyloseq::subset_samples(end, timepoint == "3Endpoint") #82 end samples

otu_table(end) <- t(otu_table(end)) #ensure OGUs are rownames
otu_table(end) <- otu_table(microbiome::abundances(end, "compositional"), taxa_are_rows =T)

tax_table(end) <- as.matrix(as.data.frame(tax_table(end)) %>% 
  mutate(across(where(is.character), str_trim)) %>%
  mutate(Phylum = str_remove(Phylum, "_[a-zA-Z]\\b")) %>%
  mutate(Genus = str_remove(Genus, "_[a-zA-Z]\\b")) %>%
  mutate(Phylum = case_when(
    Phylum == "p__" ~ "Unknown",
    str_detect(Phylum, "\\d") ~ "Unclassified",
    !str_detect(Phylum, "Actinobacteriota|Proteobacteria|Bacteroidota|Verrucomicrobiota|Campylobacterota|Firmicutes") ~ "Other",
    .default = str_remove_all(Phylum, "p__")
    )) %>%
  mutate(Genus = case_when(
    str_detect(Genus, "\\d") ~ "Unclassified",
    Genus == "g__"~ "Unknown",
    .default = str_remove_all(Genus, "g__"))))
```

### Endpoint alpha diversity

```{r eval=TRUE, label = "Endpoint Bacteria: alpha diversity"}
#assume non-parametic data to make analysis easier (dont want to remove outliers)
#subset baseline and enpoint samples
alpha.end <- microbiome::alpha(end, index = "all")

pd.end <- picante::pd(samp = as.matrix(t(otu_table(end))), tree = phy_tree(end), include.root = FALSE)
colnames(pd.end) <- c("pd", "sr")

#merge alpha metrics with metadata
bac_end_meta <- as.data.frame(as.matrix(sample_data(end)))
bac_end_meta <- bac_end_meta %>% 
  rownames_to_column () %>%
  left_join(., rownames_to_column(pd.end), by = "rowname") %>%
  left_join(., rownames_to_column(alpha.end), by = "rowname")

E.stats <- bac_end_meta %>% 
              dplyr::select(sample = rowname, timepoint, trt, observed_features = observed, chao1, diversity_shannon, evenness_pielou, pd) %>%
                pivot_longer(cols = !c(sample, timepoint, trt), names_to = "diversity_metric")

#print summary stats
E.stats %>%
  group_by(timepoint, diversity_metric) %>%
  get_summary_stats(value, type = "common")


#is there a significant difference between treatments at baseline and endpoint?
#unpaired between group comparisons: trt_base vs. ctrl_base & trt_end vs. ctrl_end     
unpaired_wilcox_endpoint <- E.stats %>%
  group_by(timepoint, diversity_metric) %>%
  pairwise_wilcox_test(value ~ trt, paired = FALSE, p.adjust.method = "BH") %>%
  add_xy_position(x = "timepoint", step.increase = 0)

#visualise as boxplot
#png(paste("07-Research_Q_analysis/03-diversity_analysis/03-Endpoint_analysis/01-Bacteria/endpoint_bacteria_alpha_stats", "Mumbai_ID14768", format(Sys.time(), "%b_%d_%Y_%I:%M"), "NC.png", sep = "_"), 1200, 800)

E.stats %>%
  group_by(diversity_metric) %>%
    ggplot(aes(x = timepoint, y = value)) +
      geom_boxplot(aes(fill = trt), outlier.shape=NA) +
      geom_jitter(size = 1.5,stat = "identity", width = 0.35) +
      facet_wrap(. ~ factor(diversity_metric), 2 ,3, scales = "free", labeller = as_labeller(plot_names)) +
      stat_pvalue_manual(unpaired_wilcox_endpoint, label = "p = {p}", step.increase = 0.05) +
      xlab(NULL) +
      ylab(NULL) +
      scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
      scale_x_discrete(labels = c("Endpoint")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 1), strip.text = element_text(size = 14, face = 'bold', color = 'black'))

#dev.off()

#rm(end, alpha.end, pd.end, bac_end_meta, E.stats,unpaired_wilcox_endpoint,plot_names)
```

```{r eval=TRUE, label = "Endpoint Bacteria: phyla relative abundance per indv"}
#base_phyla as defined in the realtive abundance boxplots above 
#collapse into phyla to make computation easier
end_genus <- microbiome::aggregate_taxa(end, level = "Genus")
end_phyla <- microbiome::aggregate_taxa(end, level = "Phylum")
#view(tax_table(base_phyla))

#top phyla at baseline for each individual
p <- plot_bar(end_phyla, fill = "Phylum")
p$data$Sample <-  str_remove_all(p$data$Sample, "SO_8465_|_E_wol_alignment|_B|_G")

#order samples Pby age
#age_labels <- baseline_metadata %>% dplyr::select(rowname, agedays_rounded) %>% mutate(rowname = str_remove_all(rowname, "SO_8465_|_B_wol_alignment|_B|_G")) %>% arrange(agedays_rounded)
#p$data$Sample <- factor(p$data$Sample, levels = age_labels$rowname)

#order by high to low Proteobacteria/Firmicutes
levels <- p$data %>% filter(Phylum == "Proteobacteria") %>% arrange(desc(Abundance))
p$data$Sample <- factor(p$data$Sample, levels = levels$Sample)


#png(paste("07-Research_Q_analysis/03-diversity_analysis/03-Endpoint_analysis/01-Bacteria/indv_endpoint_phyla_percent_reads_orderProteo", "Mumbai_ID14768", format(Sys.time(), "%b_%d_%Y_%I:%M"), "NC.png", sep = "_"), width = 2200, height = 1000)

#if looking at age, remove the '#'
p +
  geom_bar(aes(fill= forcats::fct_reorder(Phylum, Abundance)), stat="identity", position="stack")+
  scale_fill_manual(values = phyla_colours) +
  #geom_text(aes(y = max(Abundance + 0.05), label = agedays_rounded, group = Sample), angle = 90, size = 3, check_overlap = T) +
  #annotate(geom = "text", x = 84, y = 1.06, label = "Age (days)", fontface = "bold") +
  theme(axis.text.x = element_text(size = 8), plot.margin = unit(c(1,0.1,0,0), "cm"), legend.direction = "horizontal") + #unit(c(top, right, bottom, left), units)
  scale_y_continuous(expand = c(0, 0)) + #removes white space between plot and x axis
  #ylim(0, 1.06) +
  ylab("Relative Abundance")

#dev.off()
```

```{r eval=TRUE, label = "endpoint results alpha stats summary table"}
top10_genera_list <- names(sort(apply(as.data.frame(t(otu_table(end_genus))), 2, median), decreasing = T)[1:10])
top_phyla_list <- colnames(as.data.frame(t(otu_table(end_phyla))))

top10_genera <- as.data.frame(t(otu_table(end_genus))) %>% select(all_of(top10_genera_list))
#view(sort(apply(top10_genera, 2, median), decreasing = T))

bac_end_meta <- bac_end_meta %>% left_join(., rownames_to_column(as.data.frame(t(otu_table(end_phyla)))), by = "rowname") %>% left_join(., rownames_to_column(top10_genera), by = "rowname")
#view(bac_end_meta)

bac_end_meta %>%
  mutate(timepoint = case_when(
              str_detect(timepoint, "Baseline") ~ "Baseline",
              str_detect(timepoint, "Endpoint") ~ "Endpoint"
            )) %>%
  select(rowname, timepoint,trt, `Observed features` = observed, `Chao 1 Index` = chao1, `Shannon Entropy`=diversity_shannon, Evenness = evenness_pielou,`Faith's Phylogenetic Diversity` = pd, all_of(top_phyla_list),all_of(top10_genera_list)) %>%
  select(!c(rowname, Unknown)) %>%
  mutate_at(vars(`Observed features`, `Chao 1 Index`, `Shannon Entropy`, Evenness,`Faith's Phylogenetic Diversity`), as.numeric) %>%
  tbl_strata(strata = timepoint, .tbl_fun = ~ .x %>% 
    tbl_summary(
                by = trt,
                digits = everything() ~ 4, 
                missing = "no", 
                statistic = list(
	all_continuous() ~ "{median}  \n({IQR}; {min}-{max})", # stats and format for continuous columns
	all_categorical() ~ "{n} / {N}  \n({p}%)")) %>% # stats and format for categorical columns
                add_n() %>%
                add_overall() %>%
                add_p(pvalue_fun = function(x) style_pvalue(x, digits = 3)) %>%
                add_q(pvalue_fun = function(x) style_pvalue(x, digits = 3)) %>%
                bold_p(q = T)%>%
                add_stat(fns = all_continuous() ~ vda) %>%
                modify_header(list(estimate ~ "**Effect Size Estimate**", magnitude ~ "**Magnitude**")),
                .header = "**{strata}**, N = {n}") %>%
  as_kable_extra() %>%
  kable_styling(latex_options = c("striped", "scale_down"))

  #as_flex_table() %>% 
  #save_as_docx(path = "07-Research_Q_analysis/03-diversity_analysis/03-Endpoint_analysis/01-Bacteria/microbiome_endpoint_alpha_summary_tables.docx")
```

### Endpoint beta diversity

```{r eval=TRUE, label = "endpoint bacterial beta diversity"}
# Create a list to store dissimilarity matrices by timepoint and treatment group
dissimilarity_by_time_treatment <- list()

timepoints <- unique(sample_data(end)$timepoint)
distance_methods <- c("bray", "jaccard", "uunifrac", "wunifrac")

# Calculate dissimilarity for each timepoint
for (t in timepoints) {
  index <- timepoints == t
  for (method in distance_methods) {
    # Print out current timepoint and distance method for debugging
    print(paste("Timepoint:", t, "Method:", method))
    # Subset the data by timepoint
    subset_physeq_time <- phyloseq::subset_samples(end, index)
    
    # Get unique treatment groups within this timepoint
    treatments_in_timepoint <- unique(sample_data(subset_physeq_time)$trt)
  
  # Calculate Bray-Curtis dissimilarity for each treatment group within this timepoint
  for (treat in treatments_in_timepoint) {
    # Subset the data by treatment group within the timepoint
    subset_physeq_treatment <- phyloseq::subset_samples(subset_physeq_time, trt == treat)
    
    # Calculate dissimilarity
    dist_subset <- distance(subset_physeq_treatment, method = method)
    
    # Store the dissimilarity matrix in the list
    dissimilarity_by_time_treatment[[paste(t, treat, method, sep = "_")]] <- as.numeric(dist_subset)
  }
}}

betadiv0 <- data.frame(dissimilarity_by_time_treatment$`3Endpoint_0_bray`, dissimilarity_by_time_treatment$`3Endpoint_0_jaccard`, dissimilarity_by_time_treatment$`3Endpoint_0_uunifrac`, dissimilarity_by_time_treatment$`3Endpoint_0_wunifrac`)

betadiv0$id <- seq_len(nrow(betadiv0))
betadiv0 <- betadiv0 %>%
  pivot_longer(cols = -id,names_to = "variable",values_to = "value") %>%
  mutate(variable = str_remove_all(variable, "dissimilarity_by_time_treatment|\\.")) %>%
  separate(variable, into = c("timepoint", "trt", "metric"), sep = "_")%>%
  pivot_wider(names_from = metric) %>%
  select(!id)

betadiv1 <- data.frame(dissimilarity_by_time_treatment$`3Endpoint_1_bray`, dissimilarity_by_time_treatment$`3Endpoint_1_jaccard`, dissimilarity_by_time_treatment$`3Endpoint_1_uunifrac`, dissimilarity_by_time_treatment$`3Endpoint_1_wunifrac`)

betadiv1$id <- seq_len(nrow(betadiv1))
betadiv1 <- betadiv1 %>%
  pivot_longer(cols = -id,names_to = "variable",values_to = "value") %>%
  mutate(variable = str_remove_all(variable, "dissimilarity_by_time_treatment|\\.")) %>%
  separate(variable, into = c("timepoint", "trt", "metric"), sep = "_") %>%
  pivot_wider(names_from = metric) %>%
  select(!id)


betadiv <- bind_rows(betadiv0, betadiv1) 

betadiv %>% tbl_strata(strata = timepoint, .tbl_fun = ~ .x %>% 
              tbl_summary(
                by = trt,
                digits = everything() ~ 2, 
                missing = "no", 
                statistic = list(
	all_continuous() ~ "{median}  \n({IQR}; {min}-{max})", # stats and format for continuous columns
	all_categorical() ~ "{n} / {N}  \n({p}%)")) %>% # stats and format for categorical columns
                add_n() %>%
                add_overall() %>%
                add_p(test = everything() ~ "wilcox.test", group = trt, pvalue_fun = function(x) style_pvalue(x, digits = 3)) %>%
                add_q(pvalue_fun = function(x) style_pvalue(x, digits = 3)) %>%
                bold_p(q = T)%>%
                add_stat(fns = all_continuous() ~ vda) %>%
                modify_header(list(estimate ~ "**Effect Size Estimate**", magnitude ~ "**Magnitude**")),
                .header = "**{strata}**, N = {n}") %>%
    as_kable_extra() %>%
  kable_styling(latex_options = c("striped", "scale_down"))

```

```{r eval = FALSE, label = "save key files as rds to start other analyses from"}
rm(list=setdiff(ls(),c("seqdata", "seqdata_bac","seqdata_arc","metadata","taxonomy", "base_end_paired_samples")))
save.image("~/Work/05-Projects/01-Precision_nutrition/01-Methods/rarefied_sequences.RData")
```
