#!/usr/bin/env Rscript

#######################################
#                                     #
#     Alignment Statistics Analysis   #
#                                     #
#######################################

################################################################################
# Author: Nathaniel Cole (nc564@cornell.edu)                                   #
# GitHub: promicrobial (https://github.com/promicrobial)                       #
# Date: 28-01-25                                                               #
# License: MIT                                                                 #
# Version: 1.0.0                                                               #
#                                                                              #
# Description: This script extracts MAPQ scores and summary statistics from    #
# output of the `samtools stats` command. It processes quality scores and      #
# alignment statistics, calculates alignment percentages, and generates        #
# visualizations of the results.                                               #
#                                                                              #
# Dependencies:                                                                #
#   - tidyverse: For data manipulation and visualization                       #
#   - data.table: For efficient data reading and manipulation                  #
#   - reshape2: For data reshaping                                             #
# Input:                                                                       #
#   - statistics files generated by samtools stats                            #
#   Format: Standard samtools stats output                                     #
#     - Lines starting with 'MAPQ' contain mapping quality scores              #
#     - Lines starting with 'SN' contain summary statistics                    #
#                                                                              #
# Usage: Rscript alignment_stats_analysis.R [options]                          #
#   Options:                                                                   #
#     -i, --input_dir    Directory containing alignment files                  #
#     -o, --output_dir   Directory for output files                            #
#     -p, --pattern      File pattern to match (default: *.stats)              #
#                                                                              #
#                                                                              #
# Output:                                                                      #
#   - Extracted MAPQ scores (_quality.tsv)                                     #
#   - Extracted summary statistics (_summary.tsv)                              #
#   - Combined analysis results and visualizations                             #
#                                                                              #
# Last updated: 28-01-25                                                       #
################################################################################

# Options

options(warn=FALSE)

# Load required packages
required_packages <- c("tidyverse", "data.table", "reshape2", "optparse", "RColorBrewer")

# Install and load packages
load_packages <- function(packages) {
    suppressPackageStartupMessages({
        new_packages <- packages[!(packages %in% installed.packages()[,"Package"])]
        if(length(new_packages)) {
            message("Installing packages: ", paste(new_packages, collapse=", "))
            install.packages(new_packages)
        }
        invisible(lapply(packages, library, character.only = TRUE))
    })
}

load_packages(required_packages)

# Parse command line arguments
option_list <- list(
    make_option(c("-i", "--input_dir"),
                type="character",
                help="Directory containing samtools stats files"),
    make_option(c("-o", "--output_dir"),
                type="character",
                help="Output directory for results"),
    make_option(c("-p", "--pattern"),
                type="character",
                default="*.stats",
                help="File pattern to match [default=%default]")
)

opt_parser <- OptionParser(option_list=option_list)
opt <- parse_args(opt_parser)

# Validate arguments
if (is.null(opt$input_dir) || is.null(opt$output_dir)) {
    print_help(opt_parser)
    stop("Input and output directories must be specified.", call.=FALSE)
}

# Function to extract and parse MAPQ lines
extract_mapq <- function(file) {
    # Read the file
    lines <- readLines(file)
    
    # Extract lines matching MAPQ pattern
    matches <- grep("^MAPQ", lines, value = TRUE)
    
    if(length(matches) == 0) {
        warning("No MAPQ lines found in file: ", basename(file))
        return(NULL)
    }
    
    # Split the lines and create a data frame
    result <- data.frame(
        do.call(rbind, strsplit(sub("^MAPQ\t", "", matches), "\t")),
        stringsAsFactors = FALSE
    )
    
    # Add sample name and proper column names
    result$sample <- basename(tools::file_path_sans_ext(file))
    colnames(result) <- c("MAPQ_score", "count", "sample")
    
    # Convert columns to appropriate types
    result$MAPQ_score <- as.numeric(result$MAPQ_score)
    result$count <- as.numeric(result$count)
    
    return(result)
}

# Function to extract and parse summary statistics
extract_summary <- function(file) {
    # Read the file
    lines <- readLines(file)
    
    # Extract lines matching SN pattern
    matches <- grep("^SN", lines, value = TRUE)
    
    if(length(matches) == 0) {
        warning("No summary statistics found in file: ", basename(file))
        return(NULL)
    }

    # Remove the pattern prefix and split the lines to create a data frame
    result <- separate(data.frame(matches=sub("^SN\\t", "", matches)), col = matches, into = c("stat", "count", "comment"), sep = "\\t" ) 
    
    # Add sample name and proper column names
    result$sample <- basename(tools::file_path_sans_ext(file))
    colnames(result) <- c("stat", "count", "comment", "sample")
    
    return(result)
}

# Function to process all files in directory
process_stat_files <- function(input_dir, pattern = "*.stats") {
    # Get list of stat files
    stat_files <- list.files(path = input_dir, 
                            pattern = pattern, 
                            full.names = TRUE)
    
    if (length(stat_files) == 0) {
        stop("No .stats files found in directory: ", input_dir)
    }
    
    # Process each file
    message("Processing ", length(stat_files), " stat files...")
    
    # Extract MAPQ scores
    mapq_results <- lapply(stat_files, function(file) {
        message("Extracting MAPQ scores from ", basename(file))
        extract_mapq(file)
    })
    
    # Extract summary statistics
    summary_results <- lapply(stat_files, function(file) {
        message("Extracting summary statistics from ", basename(file))
        extract_summary(file)
    })
    
    # Remove NULL results
    mapq_results <- Filter(Negate(is.null), mapq_results)
    summary_results <- Filter(Negate(is.null), summary_results)
    
    # Combine results
    mapq_combined <- do.call(rbind, mapq_results)
    summary_combined <- do.call(rbind, summary_results)
    summary_combined <- summary_combined %>% 
                            mutate(stat = str_remove_all(stat, "\\:")) %>%
                            pivot_wider(id_cols = sample, names_from = stat, values_from = count)
    
    return(list(mapq = mapq_combined, summary = summary_combined))
}

# Set plot theme
fontsize <- 14
theme_set(
  theme_classic() +
    theme(
      axis.text.x = element_text(angle = 70, hjust = 1, vjust = 1, size = fontsize, face='bold', color='black'), 
      axis.text.y = element_text(size = fontsize, face='bold', color='black'),
      axis.title.x = element_text(size = fontsize, face='bold', color='black'),
      plot.title = element_text(hjust=0.5,face = "bold", size= 26),
      legend.title=element_blank(),
      legend.position = 'bottom',
      legend.text=element_text(size = fontsize, face='bold', color='black'),
      axis.title.y = element_text(size = fontsize, face='bold', color='black'),
      strip.text = element_text(size = fontsize, face = 'bold', color = 'black')
      ))

# Function to assign colors based on number of levels
assign_unique_colors <- function(char_vector, color_vector = NULL, palette = "Set2") {
  if(!require("RColorBrewer", quietly = TRUE))
    install.packages("RColorBrewer")
  library(RColorBrewer)

  unique_levels <- unique(char_vector)
  
  # If color_vector is not provided, create an empty one
  if (is.null(color_vector)) {
    color_vector <- vector("character", length = length(unique_levels))
    #names(color_vector) <- unique_levels
  }
  
  # Find levels without assigned colors
  unassigned_levels <- setdiff(unique_levels, names(color_vector))
  
  # Generate unique colors for unassigned levels
  if (length(unassigned_levels) < 9) {
    new_colors <- brewer.pal(n = length(unassigned_levels), name = palette)
  } else {
    palette <- colorRampPalette(c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a','#ffff99','#b15928'))
    new_colors <- palette(n = length(unassigned_levels))
  }
  names(new_colors) <- unassigned_levels
  
  #  Update the existing color vector with new colors for previously unseen levels
  for (level in unassigned_levels) {
    color_vector[level] <- new_colors[level]
  }

  # remove any NAs
  color_vector <- color_vector[!is.na(names(color_vector))]

  # Return the updated color vector
  return(color_vector[unique(char_vector)])
}

main <- function() {
    # Create output directory if it doesn't exist
    dir.create(opt$output_dir, showWarnings = FALSE, recursive = TRUE)
    
    # Process stat files
    message("Processing samtools stats files...")
    results <- process_stat_files(opt$input_dir, opt$pattern)
    
    # Save extracted data
    message("Saving extracted statistics...")
    write.table(results$mapq, 
                file.path(opt$output_dir, "combined_quality_scores.tsv"),
                sep = "\t", row.names = FALSE, quote = FALSE)
    write.table(results$summary,
                file.path(opt$output_dir, "combined_summary_stats.tsv"),
                sep = "\t", row.names = FALSE, quote = FALSE)
    
    # Process alignment data for visualization
    message("Processing alignment statistics...")
    alignment_stats <- results$summary %>%
        group_by(sample) %>%
        mutate(across(where(is.character), as.numeric)) %>%
        select(c(sample, `sequences`, `reads mapped`, `reads unmapped`)) %>% 
        mutate(`align percent` = `reads mapped`/sequences*100) %>%
        mutate(timepoint = case_when(
            str_detect(sample, "_B_") ~ "baseline",
            str_detect(sample, "_M_") ~ "midpoint",
            str_detect(sample, "_E_") ~ "endpoint"
        ))

    write.csv(alignment_stats, file.path(opt$output_dir, "alignment-percentages.csv"))

    # Create visualization
    message("Generating alignment percentage histogram...")
    plot <- alignment_stats %>%
        ggplot(aes(x = align_percent)) + 
          geom_histogram(aes(fill = timepoint), position = "dodge", 
                        alpha = 0.5, binwidth = 5) +
          scale_fill_manual(
                  values = assign_unique_colors(alignment_stats$timepoint),
                  name = "Timepoint"  # Legend title
              ) +
          labs(
                  x = "Percentage of sequences aligned to WoL",
                  y = "Number of samples",
              )    
    # Save results
    ggsave(file.path(opt$output_dir, "alignment_percentage_histogram.png"),
           plot = plot, width = 10, height = 7.5, dpi = 300)
    
    message("Analysis complete! Results saved in: ", opt$output_dir)
}

# Execute main function
main()